name: humanml3d
motion_dir: datasets/humanml3d/motions/AMASS_20.0_fps_nh_smplrifke_abs
annotations_dir: datasets/humanml3d/annotations/humanml3d
image_shape: [81, 263]  # Updated to match max_length
subset_size: 10  # Tiny subset for sanity check
test_samples_num: 0  # No separate test split
augment: false
grayscale: true
max_length: 81  # Updated to accommodate the time range (4.05s * 20fps = 81 frames)
n_features: 263
min_seconds: 2.0
max_seconds: 4.05
fps: 20 